     _           _            _     _   
  __| |_ __  ___| |___      _(_)___| |_ 
 / _` | '_ \/ __| __\ \ /\ / / / __| __|
| (_| | | | \__ \ |_ \ V  V /| \__ \ |_ 
 \__,_|_| |_|___/\__| \_/\_/ |_|___/\__| {1.00}

Fetching content from: http://plusbank24.pl/ ... 200 OK (23119 bytes)
Processing 195 domains ... 5 hit(s)

Original*       plusbank24.pl    91.226.117.19/Poland NS:plusmx1.polkomtel.com.pl SSDEEP:94%
Bitsquatting    qlusbank24.pl    -
Bitsquatting    rlusbank24.pl    -
Bitsquatting    tlusbank24.pl    -
Bitsquatting    xlusbank24.pl    -
Bitsquatting    0lusbank24.pl    -
Bitsquatting    pmusbank24.pl    -
Bitsquatting    pnusbank24.pl    -
Bitsquatting    phusbank24.pl    -
Bitsquatting    pdusbank24.pl    -
Bitsquatting    pltsbank24.pl    -
Bitsquatting    plwsbank24.pl    -
Bitsquatting    plqsbank24.pl    -
Bitsquatting    plesbank24.pl    -
Bitsquatting    pl5sbank24.pl    -
Bitsquatting    plurbank24.pl    -
Bitsquatting    pluqbank24.pl    -
Bitsquatting    pluwbank24.pl    -
Bitsquatting    plucbank24.pl    -
Bitsquatting    plu3bank24.pl    -
Bitsquatting    pluscank24.pl    -
Bitsquatting    plusfank24.pl    -
Bitsquatting    plusjank24.pl    -
Bitsquatting    plusrank24.pl    -
Bitsquatting    plusbcnk24.pl    -
Bitsquatting    plusbenk24.pl    -
Bitsquatting    plusbink24.pl    -
Bitsquatting    plusbqnk24.pl    -
Bitsquatting    plusbaok24.pl    -
Bitsquatting    plusbalk24.pl    -
Bitsquatting    plusbajk24.pl    -
Bitsquatting    plusbafk24.pl    -
Bitsquatting    plusbanj24.pl    -
Bitsquatting    plusbani24.pl    -
Bitsquatting    plusbano24.pl    -
Bitsquatting    plusbanc24.pl    -
Bitsquatting    plusbank34.pl    -
Bitsquatting    plusbank04.pl    -
Bitsquatting    plusbank64.pl    -
Bitsquatting    plusbankr4.pl    -
Bitsquatting    plusbank25.pl    -
Bitsquatting    plusbank26.pl    -
Bitsquatting    plusbank20.pl    -
Bitsquatting    plusbank2t.pl    -
Homoglyph       plusdank24.pl    85.128.255.105/Poland NS:ns1.nazwa.pl MX:plusdank24.pl
Homoglyph       plusbamk24.pl    -
Homoglyph       piusbank24.pl    -
Homoglyph       p1usbank24.pl    -
Hyphenation     p-lusbank24.pl   -
Hyphenation     pl-usbank24.pl   -
Hyphenation     plu-sbank24.pl   -
Hyphenation     plus-bank24.pl   -
Hyphenation     plusb-ank24.pl   -
Hyphenation     plusba-nk24.pl   -
Hyphenation     plusban-k24.pl   -
Hyphenation     plusbank-24.pl   91.239.67.99/Poland NS:ns1.dahost.pl MX:mail.plusbank-24.pl
Hyphenation     plusbank2-4.pl   -
Insertion       pklusbank24.pl   -
Insertion       plkusbank24.pl   -
Insertion       polusbank24.pl   -
Insertion       plousbank24.pl   -
Insertion       pplusbank24.pl   -
Insertion       plpusbank24.pl   -
Insertion       pl8usbank24.pl   -
Insertion       plu8sbank24.pl   -
Insertion       pliusbank24.pl   -
Insertion       pluisbank24.pl   -
Insertion       pljusbank24.pl   -
Insertion       plujsbank24.pl   -
Insertion       plhusbank24.pl   -
Insertion       pluhsbank24.pl   -
Insertion       plyusbank24.pl   -
Insertion       pluysbank24.pl   -
Insertion       pl7usbank24.pl   -
Insertion       plu7sbank24.pl   -
Insertion       pluesbank24.pl   -
Insertion       plusebank24.pl   -
Insertion       pludsbank24.pl   -
Insertion       plusdbank24.pl   -
Insertion       pluxsbank24.pl   -
Insertion       plusxbank24.pl   -
Insertion       pluzsbank24.pl   -
Insertion       pluszbank24.pl   -
Insertion       pluasbank24.pl   -
Insertion       plusabank24.pl   -
Insertion       pluwsbank24.pl   -
Insertion       pluswbank24.pl   -
Insertion       plusvbank24.pl   -
Insertion       plusbvank24.pl   -
Insertion       plusgbank24.pl   -
Insertion       plusbgank24.pl   -
Insertion       plushbank24.pl   -
Insertion       plusbhank24.pl   -
Insertion       plusnbank24.pl   -
Insertion       plusbnank24.pl   -
Insertion       plusbqank24.pl   -
Insertion       plusbaqnk24.pl   -
Insertion       plusbwank24.pl   -
Insertion       plusbawnk24.pl   -
Insertion       plusbsank24.pl   -
Insertion       plusbasnk24.pl   -
Insertion       plusbzank24.pl   -
Insertion       plusbaznk24.pl   -
Insertion       plusbabnk24.pl   -
Insertion       plusbanbk24.pl   -
Insertion       plusbahnk24.pl   -
Insertion       plusbanhk24.pl   -
Insertion       plusbajnk24.pl   -
Insertion       plusbanjk24.pl   -
Insertion       plusbamnk24.pl   -
Insertion       plusbanmk24.pl   -
Insertion       plusbanok24.pl   -
Insertion       plusbanko24.pl   -
Insertion       plusbanlk24.pl   -
Insertion       plusbankl24.pl   -
Insertion       plusbankm24.pl   -
Insertion       plusbankj24.pl   -
Insertion       plusbanik24.pl   -
Insertion       plusbanki24.pl   -
Insertion       plusbank324.pl   -
Insertion       plusbank234.pl   -
Insertion       plusbankw24.pl   -
Insertion       plusbank2w4.pl   -
Insertion       plusbankq24.pl   -
Insertion       plusbank2q4.pl   -
Insertion       plusbank124.pl   -
Insertion       plusbank214.pl   -
Omission        plsbank24.pl     -
Omission        plusbank4.pl     -
Omission        plusban24.pl     -
Omission        pusbank24.pl     -
Omission        lusbank24.pl     -
Omission        plusbnk24.pl     -
Omission        plusank24.pl     -
Omission        plusbak24.pl     -
Omission        plubank24.pl     -
Omission        plusbank2.pl     -
Repetition      plusbaank24.pl   -
Repetition      plusbbank24.pl   -
Repetition      plussbank24.pl   -
Repetition      pluusbank24.pl   -
Repetition      plusbankk24.pl   -
Repetition      plusbannk24.pl   -
Repetition      pllusbank24.pl   -
Replacement     llusbank24.pl    -
Replacement     olusbank24.pl    -
Replacement     pkusbank24.pl    -
Replacement     pousbank24.pl    -
Replacement     ppusbank24.pl    -
Replacement     pl8sbank24.pl    -
Replacement     plisbank24.pl    -
Replacement     pljsbank24.pl    -
Replacement     plhsbank24.pl    -
Replacement     plysbank24.pl    -
Replacement     pl7sbank24.pl    -
Replacement     pluebank24.pl    -
Replacement     pludbank24.pl    -
Replacement     pluxbank24.pl    -
Replacement     pluzbank24.pl    -
Replacement     pluabank24.pl    -
Replacement     plusvank24.pl    -
Replacement     plusgank24.pl    -
Replacement     plushank24.pl    -
Replacement     plusnank24.pl    -
Replacement     plusbwnk24.pl    -
Replacement     plusbsnk24.pl    -
Replacement     plusbznk24.pl    -
Replacement     plusbabk24.pl    -
Replacement     plusbahk24.pl    -
Replacement     plusbanl24.pl    -
Replacement     plusbanm24.pl    -
Replacement     plusbankw4.pl    -
Replacement     plusbankq4.pl    -
Replacement     plusbank14.pl    -
Replacement     plusbank2r.pl    -
Replacement     plusbank2e.pl    -
Replacement     plusbank23.pl    -
Subdomain       p.lusbank24.pl   -
Subdomain       pl.usbank24.pl   -
Subdomain       plu.sbank24.pl   -
Subdomain       plus.bank24.pl   72.52.4.91/United States NS:ns1.sedoparking.com MX:mail.nickstel.com
Subdomain       plusb.ank24.pl   -
Subdomain       plusba.nk24.pl   -
Subdomain       plusban.k24.pl   -
Subdomain       plusbank.24.pl   212.91.28.157/Poland NS:dns.home.pl MX:aspmx.l.google.com
Subdomain       plusbank2.4.pl   -
Transposition   lpusbank24.pl    -
Transposition   pulsbank24.pl    -
Transposition   plsubank24.pl    -
Transposition   plubsank24.pl    -
Transposition   plusabnk24.pl    -
Transposition   plusbnak24.pl    -
Transposition   plusbakn24.pl    -
Transposition   plusban2k4.pl    -
Transposition   plusbank42.pl    -
