name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip ruff setuptools wheel
      - name: "Ruff: Issues for this codebase"
        run: ruff --ignore=E402,E701,E712,E731,E741,F401,F841,W191,W605
                  --format=github --line-length=151 --target-version=py37 .
      - name: "Ruff: All issues"
        run: ruff --exit-zero --select=ALL --statistics --target-version=py37 .
      - name: "Ruff: All fixable (ruff --fix) issues"
        run: ruff --exit-zero --select=ALL --ignore=ANN204,COM812,ERA001,RSE102,RUF001
                  --statistics --target-version=py37 . | grep "\[\*\]"
      - run: pip install black codespell mypy pytest safety
      - run: black --check . || true
      - run: codespell --ignore-words-list="ans,groupe" --skip="./.*"
      - run: pip install -r requirements.txt || pip install --editable . || pip install . || true
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: safety check
